[project]
name = "pyside-uiloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyside6",
]


[tool.setuptools.packages.find]
where = ["."]
include = ["pyside-uiloader*"]